### ISSUE TITLE
Ensure temperature floor for Pop III

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#299]
Before we start running Pop III simulations, we should make sure that both chemistry and EOS do not return a temperature < T_CMB anywhere. This is important for Pop III because they are forming at very high redshifts, so the CMB temperature is not small (at z = 30, T_CMB is 83 K). In FLASH, we had to modify the EOS functions to return `max(Tgas, T_CMB)` instead of `Tgas`.

**Comment by BenWibking** [comment]
This is not physically correct. The temperature floor is numerical device designed so the code doesn't crash, not so that it doesn't cool below the temperature of the CMB.

We have a temperature floor implemented in `EnforceLimits`.

**Comment by markkrumholz** [comment]
I would suggest not using EnforceLimits to accomplish this, because, as Ben says, EnforceLimits is really intended for numerical limits, not physical ones. I would suggest that the best way to do this for now it to add an auxiliary run-time parameter to the chemistry module, which can be read from the input file, to specify the redshift, and that the CMB floor be enforced that way.

**Comment by BenWibking** [comment]
A Compton cooling/heating term should be added to the chemistry network, if it's not already there. That should have the same effect, and is the physical reason it will be close to (but not exactly) at the CMB temperature anyway.

**Comment by BenWibking** [comment]
Or the Compton term could be added in an operator split update.

**Comment by markkrumholz** [comment]
@BenWibking, while I agree that including the CMB directly in the calculation of the cooling would be better, it is actually rather hard to do right. The problem is that for most of the gas that is potentially getting near the floor, Compton heating is actually an unimportant effect, because there are very, very few free electrons; the gas is heavily neutral and molecular. As a result, the main heating effect is via the molecular lines: the CMB provides some photons at frequencies that match the frequencies of molecular lines, so there is an absorption term as well as an emission term, and if the gas is at a temperature below the CMB temperature then heating of the gas by absorption of CMB photons is more important than cooling by emission, and the gas gains energy from the radiation field. The problem with including this self-consistently in the chemisty is that the heating rate depends not just on the chemical state of the gas, but also on the distribution of levels in the molecules. One would need to do a fully self-consistent non-LTE calculation of the level populations including CMB pumping of excited states to get the heating and cooling rate really right; it's not just a simple term you can write down analytically like Compton heating is. I do calculations like that self-consistently in DESPOTIC, for example, but this is not something that would be fast enough to compute on the fly as part of the Quokka chemistry network; it would really need to be pre-tabulated.

**Comment by BenWibking** [comment]
Ah, okay. Yes, I did not realize the heating was mostly coming from molecular lines. If it's totally optically thin and there aren't too many levels (a few dozen rather than hundreds), then I think it might be feasible to do on GPUs, but it might not be worth it.

**Comment by markkrumholz** [comment]
Few levels yes, but unfortunately not optically thin, at least for the H2 lines. The HD ones might be, but it seems like a lot of computational effort for something that can be approximated pretty well as just a floor.

**Comment by BenWibking** [comment]
Ok, agreed.

**Comment by psharda** [comment]
> A Compton cooling/heating term should be added to the chemistry network, if it's not already there. That should have the same effect, and is the physical reason it will be close to (but not exactly) at the CMB temperature anyway.

It is included in the primordial chem network.

**Comment by psharda** [comment]
> I would suggest not using EnforceLimits to accomplish this, because, as Ben says, EnforceLimits is really intended for numerical limits, not physical ones. I would suggest that the best way to do this for now it to add an auxiliary run-time parameter to the chemistry module, which can be read from the input file, to specify the redshift, and that the CMB floor be enforced that way.

This is what we did in Krome in FLASH, but often the Hydro solve would return temperatures below the CMB floor (e.g., when EOS is called after a hydro sweep). Sometimes this would happen because Eint << total energy, and the subtraction of kinetic from total to find Eint would not be perfect. So, while Krome would always return a temperature >= CMB, hydro would not. Could this also be an issue for Quokka's hydro setup? More generally, we want _both_ chemistry and hydro to return temperatures >= CMB, right?

**Comment by BenWibking** [comment]
I think setting it once per timestep is probably enough, unless there are stability issues.

**Comment by BenWibking** [comment]
> > A Compton cooling/heating term should be added to the chemistry network, if it's not already there. That should have the same effect, and is the physical reason it will be close to (but not exactly) at the CMB temperature anyway.
> 
> It is included in the primordial chem network.

How does the Compton term know what the redshift is? Is this a network parameter, or is it hard-coded?

**Comment by psharda** [comment]
Redshift is a network parameter. It's defined by `z` in our python/sympy code, which we set to `Real const z = 30` in `actual_rhs.H` in Microphysics/networks/primordial_chem

**Comment by BenWibking** [comment]
I agree with Mark about making this a runtime parameter than is read using `amrex::ParmParse`.

**Comment by psharda** [comment]
This should do it: https://github.com/AMReX-Astro/Microphysics/pull/1198, and then we need to add `pc_redshift` as a runtime parameter in `tests/primordial_chem.in`

**Comment by BenWibking** [comment]
@psharda you've added this to your PopII Problem, right? If so, can we close this issue?

**Comment by psharda** [comment]
Yes
