### ISSUE TITLE
Implement AMR level-based (partial) density floor

### ISSUE THREAD

**Issue by psharda** [quokka-astro/quokka#718]
**Describe the proposal**
For stability purposes, it might be useful to consider adding a dynamic density/partial density floor, based on, say, the mean density at each AMR level. 

**Describe alternatives you've considered**
A constant floor eventually fails as density keeps rising in AMR simulations.

**Additional context**
This could prove useful in avoiding hydro crashes at very high densities / AMR levels in collapse problems (e.g., Pop III).

**Comment by markkrumholz** [comment]
I think a cleaner way to implement this, which does not require forming global sums like the mean density on a level, would be to have a floor that is linked to the local Jeans density. That is, for a given cell size and temperature, you can compute the Jeans density, and then floor if the density falls below some factor times the Jeans density. In practice this would be fairly easy to implement using the existing enforceLimits function -- you might have to add the local cell spacing as an argument to the function (can't remember if it is provided now), but other than that it should be straightforward to implement, and certainly much less work than something that requires non-local information.

**Comment by BenWibking** [comment]
> I think a cleaner way to implement this, which does not require forming global sums like the mean density on a level, would be to have a floor that is linked to the local Jeans density. That is, for a given cell size and temperature, you can compute the Jeans density, and then floor if the density falls below some factor times the Jeans density. In practice this would be fairly easy to implement using the existing enforceLimits function -- you might have to add the local cell spacing as an argument to the function (can't remember if it is provided now), but other than that it should be straightforward to implement, and certainly much less work than something that requires non-local information.

I am a little wary of the idea of making the density floor vary cell-by-cell. It seems to me like it would be hard to be sure that whenever something weird happened that you could rule out the density floor. If there's a bug or overly-aggressive relative density floor, it could erase the density gradients in a way that would not necessarily be immediately obvious.

**Comment by BenWibking** [comment]
Re: performance, I am not concerned for the PopIII sims, since reactions take 70% of the walltime.

For other cases, we can do extra reductions for free (almost) as long as they happen prior to the timestep calculation (where a reduction is require for the calculation to proceed) _and_ we use `amrex::Lazy::QueueReduction`, which coalesces all of the reductions into a single step at the point where the first non-lazy reduction (i.e., the timestep reduction) is done.

Example code from Weiqun:
```
void
CNS::printTotal () const
{
    const MultiFab& S_new = get_new_data(State_Type);
    std::array<Real,5> tot;
    for (int comp = 0; comp < 5; ++comp) {
        tot[comp] = S_new.sum(comp,true) * geom.ProbSize();
    }
    Lazy::QueueReduction( [=] () mutable {
            ParallelDescriptor::ReduceRealSum(tot.data(), 5, ParallelDescriptor::IOProcessorNumber());
            amrex::Print().SetPrecision(17) << "\n[CNS] Total mass       is " << tot[0] << "\n"
                                            <<   "      Total x-momentum is " << tot[1] << "\n"
                                            <<   "      Total y-momentum is " << tot[2] << "\n"
                                            <<   "      Total z-momentum is " << tot[3] << "\n"
                                            <<   "      Total energy     is " << tot[4] << "\n";
        });
}
```

So, in principle, this avoids adding any extra latency due to the lazy reductions. (Of course, the MPI implementation can always do something dumb that might make this untrue in practice.)

**Comment by markkrumholz** [comment]
Not sure having it vary over time is any better than having it vary from cell to cell -- but if one wanted not to have it vary from cell to cell or over time, one could calculate the Jeans density using the floor temperature instead of the actual gas temperature. In that case it depends only on the cell size, and thus is the same for all cells on a level.

**Comment by BenWibking** [comment]
That seems workable. For a non-gamma-law gas, we still need to specify a density and chemical state in order to compute the sound speed. Or is there a way to avoid that (i.e., assume it is a gamma-law gas only for this purpose)?

**Comment by markkrumholz** [comment]
Fair point. Yes, if we want the floor not to vary with position and time, we probably have to supply a fixed mean particle mass for the purposes of turning the temperature floor into an isothermal sound speed -- and it is probably better practice in general to use the isothermal than the adiabatic sound speed when computing the Jeans density, since Jeans instability can only run away to collapse to very large densities if the gas is close to isothermal.

**Comment by BenWibking** [comment]
Ok, so @psharda and I figured out that the most likely cause of the crashes was that this line only applies the partial density floor if the partial densities are negative (rather than just less than the floor value):

https://github.com/quokka-astro/quokka/blob/86686408835cf731c5792151bb890f6c6f78b2fc/src/hydro/hydro_system.hpp#L729

This should be easy to fix, and hopefully will avoid the need for the level-dependent floors.

**Comment by psharda** [comment]
> Ok, so @psharda and I figured out that the most likely cause of the crashes was that this line only applies the partial density floor if the partial densities are negative (rather than just less than the floor value):
> 
> https://github.com/quokka-astro/quokka/blob/86686408835cf731c5792151bb890f6c6f78b2fc/src/hydro/hydro_system.hpp#L729
> 
> This should be easy to fix, and hopefully will avoid the need for the level-dependent floors.

Doing this does not lead to a fatal FOFC crash anymore, but leads to several FOFC-2 warnings in > 1000 cells across different levels.

A simpler fix Ben and I found good enough was to turn off the fatal crash by using `hydro.abort_on_fofc_failure = 0`. The simulation has progressed more than 5000 steps since, and also refined to more AMR levels, and the gas properties look reasonable. So we do not need to implement level-based partial density floors, at least in the context of PopIII.

**Comment by BenWibking** [comment]
This appears to be fixed for Piyush's simulations, so I'll go ahead and close this.
